additional_guides:
    https://github.com/sobri909/MGBoxKit/wiki/Basic-Concepts-and-Introduction
    https://github.com/sobri909/MGBoxKit/wiki/Positioning-and-Layout-Guide
    https://github.com/sobri909/MGBoxKit/wiki/Tables-and-Grids-Guide
    
